---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: picalc-deployment
  labels:
    app: picalc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: picalc
  template:
    metadata:
      labels:
        app: picalc
    spec:
      containers:
      - name: picalc-pod
        image: drehnstrom/pi-calc:v1.0
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "512Mi"
            cpu: ".25"
          limits:
            memory: "1024Mi"
            cpu: ".5"

---
apiVersion: v1
kind: Service
metadata:
  name: picalc-service
  labels:
    app: picalc
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: picalc
 
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: picalc-deployment-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v2beta1
    kind: Deployment
    name: picalc-deployment
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 60
      
      
